language:
  - objective-c

osx_image: xcode7.1

before_install:
    - brew update
    - brew install carthage

matrix:
  include:
    - xcode_workspace: UnzipKit.xcworkspace
      xcode_scheme: UnzipKit
      xcode_sdk: macosx
      env: NAME=Mac; TEST=test

    - xcode_workspace: UnzipKit.xcworkspace
      xcode_scheme: UnzipKit-iOS
      xcode_sdk: iphonesimulator
      env: Name=iOS

    - xcode_workspace: UnzipKitDemo/UnzipKitDemo.xcworkspace
      xcode_scheme: UnzipKitDemo
      xcode_sdk: iphonesimulator
      env: NAME=DemoAppBuild

before_script:
  - brew install carthage

script:
  - xctool -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK analyze -configuration Release $TEST ENABLE_NS_ASSERTIONS=1
  - ./Scripts/carthage-validate.sh
  - ./Scripts/cocoapod-validate.sh

# Turn on Docker, container-based infrastructure
sudo: false