language:
  - objective-c

matrix:
  include:
    - xcode_workspace: UnzipKit.xcworkspace
      xcode_scheme: UnzipKit
      xcode_sdk: macosx
      env: SHOULDTEST=test

    - xcode_workspace: UnzipKit.xcworkspace
      xcode_scheme: UnzipKit
      xcode_sdk: macosx10.9
      env: SHOULDTEST=

    - xcode_workspace: UnzipKitDemo/UnzipKitDemo.xcworkspace
      xcode_scheme: UnzipKitDemo
      xcode_sdk: iphonesimulator
      env: SHOULDTEST=test

before_script:
  - ./Scripts/install-demo-libs.sh

script:
  - set
  - xctool -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -configuration Release analyze $SHOULDTEST

after_script:
  - ./Scripts/cocoapod-validate.sh

# Turn on Docker, container-based infrastructure
sudo: false