language: objective-c

xcode_workspace: UnzipKit.xcworkspace
xcode_scheme: UnzipKit

xcode_sdk:
  - macosx
  - macosx10.9

script:
  - xctool -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -configuration Release analyze test
#  - xctool -workspace UnzipKit.xcworkspace -scheme UnzipExample -sdk iphonesimulator build

after_script:
  - ./Scripts/cocoapod-validate.sh

# Turn on Docker, container-based infrastructure
sudo: false