language:
  - objective-c
  - swift

xcode_workspace:
  - UnzipKit.xcworkspace
  - UnzipKitDemo/UnzipKitDemo.xcworkspace

xcode_scheme:
  - UnzipKit
  - UnzipKitDemo

xcode_sdk:
  - macosx
  - macosx10.9
  - iphonesimulator
  - iphonesimulator7.1

before_script:
  - pushd UnzipKitDemo; pod install; popd

script:
  - xctool -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -configuration Release analyze test

after_script:
  - ./Scripts/cocoapod-validate.sh

matrix:
  exclude:
    - xcode_workspace: UnzipKit.xcworkspace
      xcode_scheme: UnzipKitDemo
    - xcode_workspace: UnzipKitDemo/UnzipKitDemo.xcworkspace
      xcode_scheme: UnzipKit
    - xcode_workspace: UnzipKit.xcworkspace
      language: swift
    - xcode_workspace: UnzipKitDemo/UnzipKitDemo.xcworkspace
      language: objective-c
    - xcode_scheme: UnzipKit
      xcode_sdk: iphonesimulator
    - xcode_scheme: UnzipKit
      xcode_sdk: iphonesimulator7.1
    - xcode_scheme: UnzipKitDemo
      xcode_sdk: macosx
    - xcode_scheme: UnzipKitDemo
      xcode_sdk: macosx10.9

# Turn on Docker, container-based infrastructure
sudo: false