language: objective-c
script:
  - xctool -workspace UnzipKit.xcworkspace -scheme UnzipKit -configuration Release build test
#  - xctool -workspace UnzipKit.xcworkspace -scheme UnzipExample -sdk iphonesimulator build
#  - ./Scripts/cocoapod-validate.sh