language:
  - objective-c

# Required, for now, to use Swift 1.2
osx_image: beta-xcode6.3

matrix:
  include:
    - xcode_workspace: UnzipKit.xcworkspace
      xcode_scheme: UnzipKit
      xcode_sdk: macosx
      env: TEST=test

    - xcode_workspace: UnzipKit.xcworkspace
      xcode_scheme: UnzipKit
      xcode_sdk: macosx10.9
      env: NAME=MavericksBuild

    - xcode_workspace: UnzipKitDemo/UnzipKitDemo.xcworkspace
      xcode_scheme: UnzipKitDemo
      xcode_sdk: iphonesimulator
      env: NAME=DemoAppBuild

before_script:
  - ./Scripts/install-demo-libs.sh

script:
  - xctool -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK analyze $TEST ENABLE_NS_ASSERTIONS=1

after_script:
  - ./Scripts/cocoapod-validate.sh

# Turn on Docker, container-based infrastructure
sudo: false